Fix/move to common build
nullean/proc pull request #5
Opened 2020-05-15 19:36 UTC by Mpdreamz

Todo 

- [ ] the old build assembly rewrote and IL linked in RX.NET.
- [ ] Make sure other dependencies are limited per TFM

```
[framework] .NETFramework4.5
[dependency] .NETFramework4.5, Id:Microsoft.NETFramework.ReferenceAssemblies.net45, Version:1.0.0 @include=All
[dependency] .NETFramework4.5, Id:Microsoft.NETFramework.ReferenceAssemblies.net46, Version:1.0.0 @include=All
[dependency] .NETFramework4.5, Id:System.Reactive.Linq, Version:4.0.0-preview00001 @exclude=Build,Analyzers
[dependency] .NETFramework4.5, Id:Microsoft.NETFramework.ReferenceAssemblies.net45, Version:1.0.0 @include=All
[dependency] .NETFramework4.5, Id:Microsoft.NETFramework.ReferenceAssemblies.net46, Version:1.0.0 @include=All
[dependency] .NETFramework4.5, Id:System.Reactive.Linq, Version:4.0.0-preview00001 @exclude=Build,Analyzers
[dependency] .NETFramework4.5, Id:Microsoft.NETFramework.ReferenceAssemblies.net45, Version:1.0.0 @include=All
[dependency] .NETFramework4.5, Id:Microsoft.NETFramework.ReferenceAssemblies.net46, Version:1.0.0 @include=All
[dependency] .NETFramework4.5, Id:System.Diagnostics.Process, Version:4.3.0 @exclude=Build,Analyzers
[dependency] .NETFramework4.5, Id:System.Reactive.Linq, Version:4.0.0-preview00001 @exclude=Build,Analyzers
[dependency] .NETFramework4.5, Id:System.Threading.Thread, Version:4.3.0 @exclude=Build,Analyzers

[framework] .NETFramework4.6
[dependency] .NETFramework4.6, Id:Microsoft.NETFramework.ReferenceAssemblies.net45, Version:1.0.0 @include=All
[dependency] .NETFramework4.6, Id:Microsoft.NETFramework.ReferenceAssemblies.net46, Version:1.0.0 @include=All
[dependency] .NETFramework4.6, Id:System.Reactive.Linq, Version:4.0.0-preview00001 @exclude=Build,Analyzers
[dependency] .NETFramework4.6, Id:Microsoft.NETFramework.ReferenceAssemblies.net45, Version:1.0.0 @include=All
[dependency] .NETFramework4.6, Id:Microsoft.NETFramework.ReferenceAssemblies.net46, Version:1.0.0 @include=All
[dependency] .NETFramework4.6, Id:System.Reactive.Linq, Version:4.0.0-preview00001 @exclude=Build,Analyzers
[dependency] .NETFramework4.6, Id:Microsoft.NETFramework.ReferenceAssemblies.net45, Version:1.0.0 @include=All
[dependency] .NETFramework4.6, Id:Microsoft.NETFramework.ReferenceAssemblies.net46, Version:1.0.0 @include=All
[dependency] .NETFramework4.6, Id:System.Diagnostics.Process, Version:4.3.0 @exclude=Build,Analyzers
[dependency] .NETFramework4.6, Id:System.Reactive.Linq, Version:4.0.0-preview00001 @exclude=Build,Analyzers
[dependency] .NETFramework4.6, Id:System.Threading.Thread, Version:4.3.0 @exclude=Build,Analyzers

[framework] .NETStandard2.0
[dependency] .NETStandard2.0, Id:Microsoft.NETFramework.ReferenceAssemblies.net45, Version:1.0.0 @include=All
[dependency] .NETStandard2.0, Id:Microsoft.NETFramework.ReferenceAssemblies.net46, Version:1.0.0 @include=All
[dependency] .NETStandard2.0, Id:System.Reactive.Linq, Version:4.0.0-preview00001 @exclude=Build,Analyzers
[dependency] .NETStandard2.0, Id:Microsoft.NETFramework.ReferenceAssemblies.net45, Version:1.0.0 @include=All
[dependency] .NETStandard2.0, Id:Microsoft.NETFramework.ReferenceAssemblies.net46, Version:1.0.0 @include=All
[dependency] .NETStandard2.0, Id:System.Reactive.Linq, Version:4.0.0-preview00001 @exclude=Build,Analyzers
[dependency] .NETStandard2.0, Id:Microsoft.NETFramework.ReferenceAssemblies.net45, Version:1.0.0 @include=All
[dependency] .NETStandard2.0, Id:Microsoft.NETFramework.ReferenceAssemblies.net46, Version:1.0.0 @include=All
[dependency] .NETStandard2.0, Id:System.Diagnostics.Process, Version:4.3.0 @exclude=Build,Analyzers
[dependency] .NETStandard2.0, Id:System.Reactive.Linq, Version:4.0.0-preview00001 @exclude=Build,Analyzers
[dependency] .NETStandard2.0, Id:System.Threading.Thread, Version:4.3.0 @exclude=Build,Analyzers
```

2020-05-15 19:49 UTC, Mpdreamz commented
The dependency listing turned out be a bug in `npkg-validator` https://github.com/nullean/nupkg-validator/pull/5

2020-11-18 08:04 UTC, stevejgordon requested changes
A couple of the packages can be bumped to our latest releases but otherwise LGTM.

2020-11-18 08:04 UTC, stevejgordon commented on dotnet-tools.json
> +      "version": "0.2.2",
Could now use 0.3.0

2020-11-18 08:04 UTC, stevejgordon commented on dotnet-tools.json
> +      "version": "0.11.2",
Could now use 0.13.0

2020-11-18 10:55 UTC, Mpdreamz commented
Good catch @stevejgordon updated the tooling to latest too.

2020-11-18 11:10 UTC, stevejgordon approved these changes
LGTM

2020-11-18 11:22 UTC, merged